version: '3.9'
services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=mozio
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgis_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mozio"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure
    volumes:
      - .:/app    

volumes:
  postgis_db:
  redisdata:    